### ISSUE TITLE
Allow cards to be configured per project

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#101]
The card set shall be configurable globally (existing feature) and be overwritten in the project specific configuration. If there is a project specific card set defined this shall be used in favor of the globally defined one.

**Tasks**

- [x] project configuration for card set
- [x] create session with project specific card set and use globally defined card set as a default
- [x] internationalize configuration
- [x] update online documentation

**Comment by neilgower** [comment]
Its great that the new version you can choose the cards now. What would be really useful is the ability to set a standard in the add-in configuration and then at a project level be able to choose to use the default or input a different progression.

The reason is that some of our projects use simple T-Shirt sizing, so whist some teams will use Story points, some will use Small/Medium/Large etc

It would also be great to be able to able at a project level to specify the available fields and the specific cards for that field...  e.g.

1. Estimation Field: Story Points      Card Set: 1,2,3,8,13,21
2. Estimation Field: T-Shirt Size       Card Set: Small, Medium, Large, X-Large
3..

and so on

**Comment by codescape** [comment]
Hi @neilgower,

this is exactly what I have planned for future implementations. Next steps will be 

* #102 to allow non numeric values like t-shirt sizes
* #101 to configure cards per project
* #103 to configure the estimation field per project

I hope that helps! And more to come :)

**Comment by neilgower** [comment]
Cool looks good. One question are there any plans to allow multiple stories
per session

**Comment by codescape** [comment]
> Cool looks good. One question are there any plans to allow multiple stories per session

#61 is a similar request and I recently got another request for a bulk start functionality. At the moment the features listed above have higher priority.

**Comment by neilgower** [comment]
Understand that things need to be done by priority, what you are planning
and delivering is really improving the app, it's getting very good

Neil

**Comment by codescape** [comment]
Got another feedback requesting this feature.
