### ISSUE TITLE
Allow non-numeric values to be chosen and confirmed

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#102]
Ignore coffee and question strings and allow all other values to be assigned.

**Tasks**

- [x] calculate need to talk flag correctly
- [x] allow to persist non numeric values into custom fields
- [x] validate configuration and return non-assignable values

**Out of scope**

* #112

**Comment by codescape** [comment]
**Inspiration**

* https://bitbucket.org/tngtech-atlassian-add-ons/barcharts-for-jira/pull-requests/5/support-derived-custom-fields-by-checking/diff

**Snippets**

        CustomField customField = estimationFieldService.findStoryPointField();
        try {
            System.out.println("CustomField " + customField);
            // CustomField Story-Punkte
            System.out.println("CustomFieldType " + customField.getCustomFieldType());
            // CustomFieldType com.atlassian.jira.issue.customfields.impl.NumberCFType@13bf74e9
        } catch (Exception ignore) { }

**Comment by codescape** [comment]
- [ ] validate configuration and return non-assignable values
