### ISSUE TITLE
Workflow Post Function to start Scrum Poker session

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#104]
Start a new Scrum Poker session for an issue automatically when the issue changes its status on a defined workflow transation.

**Tasks**

- [x] implement workflow function
- [x] check for valid license in workflow function
- [x] add online documentation for workflow function

**Documentation**

* https://developer.atlassian.com/server/jira/platform/creating-workflow-extensions/#part-2--create-the-workflow-post-function

**Comment by codescape** [comment]
Further ideas:

* add a workflow condition that only allows transition if a completed Scrum Poker session exists

**Comment by codescape** [comment]
released with 20.06.2
