### ISSUE TITLE
Getting Started Page for Scrum Poker for Jira

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#123]
Add a **Getting Started** page that helps to get started after installation or update.

**Draft**

> **Introduction**
> 
> Scrum Poker for Jira enables your agile teams to collaboratively estimate their work items using a clean and interactive user interface that is seamlessly integrated into Jira Software.
> 
> **First Steps**
> 
> _The elements listed below shall include a small description how to archive that task until they are marked as completed with a green checkmark_
> 
> * Configure a valid license for Scrum Poker for Jira
> * Provide required configuration for Scrum Poker for Jira
> * Start your first Scrum Poker session
>
> **What's new?**
>
>  _Add reference to changelog_
>
> **Need support?**
>
> _Add a reference to the official documentation at https://jira-scrum-poker.codescape.de and direct link to the support page at https://jira-scrum-poker.codescape.de/support for contact options and the issue tracker on https://github.com/codescape/jira-scrum-poker/issues to raise an issue if one found a bug._

**Tasks**

- [x] create page
- [x] introduce Scrum Poker for Jira briefly
- [x] include logo :)
- [x] link to official documentation and support page
- [x] lead user to configuration, health check and error log
- [x] change post install and post update url and lead to this page

**Comment by codescape** [comment]
- [x] test compatibility of aui css with older versions of Jira
