### ISSUE TITLE
Extract license check into separate class

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#131]
We should offer two methods `boolean isLicensed()` and `String getLicenseError()` to be used as shown here:

    @Override
    protected String doExecute() {
        if (!licenseService.isLicensed()) {
            errorMessage("Unable to start session because of license error: " + licenseService.getLicenseError());
            return ERROR;
        }
        ...
    }

**Tasks**

- [x] implement service
- [x] test service
- [x] use in ScrumPokerAction
- [x] use in ScrumPokerHealthCheck ?
- [x] use in StartSessionWorkflowFunction
