### ISSUE TITLE
Provide active sessions as a dashboad gadget

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#134]
Allow to jump into scrum poker sessions from a Jira dashboard gadget that shows running Scrum Poker sessions. Optionally this could be customized with a filter to a specific project or query.

**Tasks**

- [ ] create the gadget
- [ ] (optional) i18n for the gadget
- [ ] (optional) configuration for the gadget
- [ ] update/create online documentation

**Related**

* https://developer.atlassian.com/server/jira/platform/writing-gadgets-for-jira/
