### ISSUE TITLE
Allow to use Scrum Poker for Jira for estimates on the time tracking fields

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#146]
Users want to use Scrum Poker for Jira to estimate for their time tracking, too. To allow users to do so we need to allow cards with values like 4h, 8h, 2d, 3d, 1w and we would set them on the issue when they are accepted.

**Tasks**

- [ ] update [faq](https://jira-scrum-poker.codescape.de/faq)
- [ ] update [supported fields](https://jira-scrum-poker.codescape.de/configuration#confirmed-estimate-field)
- [ ] implement mapping of estimate values to estimate field (see [EstimateStringService in Multiple Subtasks for Jira](https://github.com/codescape/jira-multiple-subtasks/blob/master/src/main/java/de/codescape/jira/plugins/multiplesubtasks/service/syntax/EstimateStringService.java))

**User requests**

* https://codescape.atlassian.net/browse/CASUP-91
