### ISSUE TITLE
Allow cards to be configured globally

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#18]
We would like to choose the cards to be used per project since not all teams want to use the Fibonacci sequence for estimation.

* default card set configurable in plugin settings
* concrete card set configurable in board or project configuration
* list of supported card sets can be configured in plugin settings

**Tasks**

- [x] create Active Object ScrumPokerCardSet to persist card sets with the following fields: displayName, valueList, hasQuestionMark, hasCoffeeCard
- [x] associate every ScrumPokerSession with a ScrumPokerCardSet
- [x] load ScrumPokerCardSet together with the ScrumPokerSession and populate it
- [x] create upgrade task to populate sample card sets and set default card set
  - Fibonacci Sequence; 0,1,2,3,5,8,13,20,40,100; with question mark; with coffee card
  - Working Hours; 0,1,2,4,8,16; with question mark; with coffee card
  - Working Days; 0,1,2,3,4,5; with question mark; with coffee card
- [x] make card sets editable and allow to create new card sets using [Select2](https://select2.org/tagging)
- [ ] ensure correct styling for cards with longer text as the label

**Scoping**

* First iteration: only globally configurable
* Second iteration: configurable per project

**Comment by maxammann** [comment]
I would like this feature very much. As the deck could differ between projects and teams this should be configurable per project as defined in the issue.

Right now I can think of those decks:

- Fibonacci
- T-Shirts
- Days
- Working hours
- Yes/No
- (custom decks)

**Comment by codescape** [comment]
Thank you for your comment, @maxammann! I will start refactoring out the card deck into configurable   assets soon but until now I am unsure how to address the fact that the default estimation field is a number only field. So one would need to configure another target field for the estimation with the chosen set.

**Comment by maxammann** [comment]
For some card decks a number would probably be not enough yes. I think starting with Fibonacci, Days, Working hours and a set of custom numbers would be enough. I think it is not a problem if other values are possible to set.

**Comment by codescape** [comment]
First iteration done: 883eefae4057adabe22ebeebc16bf75fbce5bdfb

**Comment by codescape** [comment]
Next version will come with a configurable card set.

**Comment by codescape** [comment]
Closing this issue and rising a new issue for project specific card sets.
