### ISSUE TITLE
Show additional fields for issue

### ISSUE THREAD

**Issue by ralfsch** [codescape/jira-scrum-poker#21]
We have some additional fields that we would like to see in the poker session, e. g. we have a separate field for the acceptance criterias. Maybe the list of fields to show could be configurable?

**Comment by codescape** [comment]
Thank you very much. I need to find some good place to make this configurable since fields can possibly vary between issuetypes and projects.

**Comment by ralfsch** [comment]
Would it be possible to configure this in the field configuration?

**Comment by codescape** [comment]
Idea would be to make it configurable like the fields and rows in the Xray add-on.

![image](https://user-images.githubusercontent.com/398901/43317314-a92113b4-919c-11e8-9731-bfce6d0666c9.png)

**Comment by winden** [comment]
I suggest that in a plugin setting we have a default field. But it could be overwritten during the session. We use planning poker approach for many firlds: Risk Reduction, Business Value, Story Points, Time Criticality
![new wireframe 1](https://user-images.githubusercontent.com/831031/45502074-46ba1880-b783-11e8-8fa7-996ff7e89a22.png)

**Comment by codescape** [comment]
Hello @winden, thank you for your comment and idea. I will think about this and how it might be implemented. One should not allow every participant to change the field and I would limit this to the creator of the Scrum Poker session.

**Comment by winden** [comment]
hey @codescape, usually planning poker practice used by Agile teams with a solid level of trust. Part of being agile and working on an agile team is the ability to work cross-functionally and share ownership. Besides the changes of values are reflected in an issue history and logs; so IMHO an argument that only the creator can change the field is impractical and, perhaps, creates more problems than resolves. 

To some degree, we risk of getting the same situation as Atlassian got into with permission to start sprints and then had to make it separate permission https://www.atlassian.com/blog/jira-software/jira-software-sprint-permissions

To add to shared ownership trend Atlassian has recently announced another warmly welcomed change: https://jira.atlassian.com/browse/JRASERVER-17783

**Comment by codescape** [comment]
Hey @winden, everything is fine with your argumentation but I still aim to have a simple and effective user interface to support users of all levels in estimating their work. I do not want to limit users but want to keep away distraction if possible - but not at all costs - if a feature is worth it I have no problems in doing so and adding required complexity.

btw: This issue started with the request for new fields being displayed for the issue in question and not for more fields to write the resulting estimation into.

**Comment by neilgower** [comment]
Totally agree with this, we have key firlds for acceptance criteria, we have the envision plugin etc.
Perhaps the option to show the actual story on the left hand side in a Div or similar. At the moment we flip between the story and the session in order to be able to see the details needed to size the story

This config should be in the add-on config as a default, but projects should be able to override and set their own config at a project level.

**Comment by awgeorge** [comment]
I would like to display our custom `Acceptance Criteria` field on this screen too. Would probably be great if you could just load all the information from the main issue panel.

**Comment by codescape** [comment]
I will try to find a solution for one of the next releases of Scrum Poker for Jira - either display the fields of the issue screen or make this configuration available.

**Comment by codescape** [comment]
I just stared with the development of this feature...

currently it looks like this:

![image](https://user-images.githubusercontent.com/398901/94998150-f4d5cc80-05af-11eb-94dd-3106023389cf.png)

**Tasks**

Required for minimum viable product:

- [x] allow to add custom fields to the list of displayed fields
- [x] allow to remove custom fields from the list of displayed fields
- [x] show configured fields on session view
- [x] add internationalization for "Details" heading
- [x] consider fields can be deleted but still be configured
- [x] test with no custom field configured
- [x] add unit tests for new AdditionalFieldService class
- [x] add internationalization for configuration
- [x] keep other changes on the configuration page when adding or removing a field?
- [x] only show fields not yet configured

Later improvements:

- [x] submit the fields in the order they are displayed (see https://www.j-tricks.com/tutorials/one-fixversion-please)
- [ ] also allow to add the standard fields
- [ ] show configured fields on session view only when value exists

**Comment by codescape** [comment]
This feature will be released in the next version of Scrum Poker for Jira!
