### ISSUE TITLE
Check for permission of the current user to save estimation

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#68]
As an administrator for a Jira instance I want to make sure that users cannot add estimations to an issue when they have no permission to edit the issue.

_This feature request is extracted from a customer mail._

**Affected code**

https://github.com/codescape/jira-scrum-poker/blob/76a3b7979bbd0020a79d2856110d066ec3bff707/src/main/java/de/codescape/jira/plugins/scrumpoker/service/EstimationFieldService.java#L49

**Solution**

Check the permission before updating:

    permissionManager.hasPermission(ProjectPermissions.EDIT_ISSUES,issue, applicationUser);

**Tasks**

- [x] verify permissions of the current user to write the field
- [x] do not render clickable estimates when user is not allowed
- [x] add upgrade method to set the default value (false)

**Comment by codescape** [comment]
Released with version 4.2.0
