### ISSUE TITLE
Collect errors in add-on specific database table

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#69]
To help Jira administrators with Scrum Poker for Jira and be able to provide better support I want to create a table that holds recent errors with the Scrum Poker for Jira app. Jira administrators shall be able to see those errors and provide them when asking for support with the required information attached:

* Stacktrace
* Jira version
* Add-on version
* Timestamp
* Type (Error, Warning)

**Tasks**

- [x] extend Health Check and verify error log does not contain critical errors 
- [x] allow to see entries in error log (in Health Check?)
- [x] allow to empty the error log if entries exist
- [x] log all potential errors that currently exist
- [x] add translation for error log page
- [x] add online documentation

**Comment by codescape** [comment]
We can collect errors and warnings in this table.

**Comment by codescape** [comment]
We should create documentation pages for typical errors collected in this error log.
