### ISSUE TITLE
Show running Scrum Poker session and button to join on Issue Detail View

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#78]
When a Scrum Poker session is currently running for the issue the issue detail page is displayed for there should be a new web element that informs about a running session and allows to join with one click.

See tutorial for details: https://developer.atlassian.com/server/jira/platform/adding-content-to-the-jira-view-issue-page/

**Tasks**

- [ ] create web element that allows to join / create a Scrum Poker session
- [ ] render web element only if an active session exists (configurable?)
- [ ] add internationalization for all texts

**Comment by codescape** [comment]
**Ideas**

For active sessions that are currently running show: 

* number of participants
* started by
* start date

For active sessions that are recently finished show:

* number of participants
* agreed estimate
* confirmed date

**Comment by codescape** [comment]
Development happens here:

https://github.com/codescape/jira-scrum-poker/tree/issue-detail
