### ISSUE TITLE
Show issue comments on Scrum Poker session page

### ISSUE THREAD

**Issue by codescape** [codescape/jira-scrum-poker#83]
While on the Scrum Poker session page show all comments for the current issue as they might help to provide an estimate.

**Tasks**

- [x] configuration option to show/hide comments (mark feature as beta)
- [x] translate all texts into all supported languages
- [x] fallback when the wiki renderer cannot be resolved?
- [x] translate configuration options into all supported languages
- [x] create online documentation for configuration options
- [ ] update screenshots for Scrum Poker session page

**Related ideas**

* pagination / limit comments displayed
* configuration option to show/hide sub tasks
* own css for issue list (active sessions page) / sub task list (session page)

**Comment by codescape** [comment]
First iteration in 84854cd74a6b4a9be2ceac07b2e5aeaabec57e19

**Comment by codescape** [comment]
Configration comes with e382c8cfbef57b211fd6e2be36eff8c9ed8ca9cf

**Comment by codescape** [comment]
Documentation in 1a114dee057f266af21e07ee5ee290c7036d6ba6

**Comment by codescape** [comment]
included in release 4.6.0
